image: frysch/ubuntu:ocl-intel

# compile examples

build-setupVisualizer:
  stage: build
  script:
    - cd examples/setupVisualizer
    - qmake
    - make

build-simTool:
  stage: build
  script:
    - cd examples/simTool
    - qmake
    - make
    
build-simTool-Debug:
  stage: build
  script:
    - cd examples/simTool
    - qmake CONFIG+=debug
    - make

build-readmeTeaser:
  stage: build
  script:
    - cd examples/readme-example
    - qmake
    - make


# unit testing

build-unitTests:
  stage: build
  script:
    - cd testing/src
    - qmake
    - make
  artifacts:
    paths:
      - testing/src/bin/

run-unitTests:
  stage: test
  script:
    - cd testing/src/bin
    - ./unitTesting


# trigger building of documentation

run-doxygen:
  stage: build
  script:
    - apt-get update
    - apt-get install -y lynx
    - wget -q -O start-doxy $INITIATE_DOXY_SCRIPT
    - lynx -cmd_script=start-doxy $DOXY_LOGIN_PAGE > /dev/null
