image: frysch/ubuntu:ocl-intel


# compile examples

build-2D3DRegistration:
  stage: build
  script:
    - git clone https://github.com/stevengj/nlopt.git
    - cd nlopt
    - cmake . && make && make install
    - cd ../examples/regist2d3d
    - qmake
    - make

build-3DRadonTransform:
  stage: build
  script:
    - cd examples/radon3d
    - qmake
    - make

build-meanProjectionDistance:
  stage: build
  script:
    - cd examples/mpd
    - qmake
    - make

build-projectionMatrices:
  stage: build
  script:
    - cd examples/using-projection-matrices
    - qmake
    - make

build-readmeTeaser:
  stage: build
  script:
    - cd examples/readme-example
    - qmake
    - make

build-setupVisualizer:
  stage: build
  script:
    - cd examples/setupVisualizer
    - qmake
    - make

build-simTool:
  stage: build
  script:
    - cd examples/simTool
    - qmake
    - make
    
build-simTool-Debug:
  stage: build
  script:
    - cd examples/simTool
    - qmake CONFIG+=debug
    - make


# unit testing

build-unitTests:
  stage: build
  script:
    - cd testing/src
    - qmake
    - make
  artifacts:
    paths:
      - testing/src/bin/

run-unitTests:
  stage: test
  script:
    - cd testing/src/bin
    - ./unitTesting


# trigger building of documentation

run-doxygen:
  stage: build
  script:
    - wget -q -O start-doxy $INITIATE_DOXY_SCRIPT
    - lynx -cmd_script=start-doxy $DOXY_LOGIN_PAGE > /dev/null
