image: frysch/ubuntu:ocl-intel


# compile examples

build-2D3DRegistration:
  stage: build
  script:
    - git clone https://github.com/stevengj/nlopt.git
    - cd nlopt
    - cmake .
    - cmake --build . --target install
    - cd ../examples/regist2d3d
    - qmake
    - make
build-2D3DRegistration-clang:
  stage: build
  script:
    - git clone https://github.com/stevengj/nlopt.git
    - cd nlopt
    - cmake .
    - cmake --build . --target install
    - cd ../examples/regist2d3d
    - qmake -spec linux-clang
    - make

build-3DRadonTransform:
  stage: build
  script:
    - cd examples/radon3d
    - qmake
    - make
build-3DRadonTransform-clang:
  stage: build
  script:
    - cd examples/radon3d
    - qmake -spec linux-clang
    - make

build-meanProjectionDistance:
  stage: build
  script:
    - cd examples/mpd
    - qmake
    - make
build-meanProjectionDistance-clang:
  stage: build
  script:
    - cd examples/mpd
    - qmake -spec linux-clang
    - make

build-projectionMatrices:
  stage: build
  script:
    - cd examples/using-projection-matrices
    - qmake
    - make
build-projectionMatrices-clang:
  stage: build
  script:
    - cd examples/using-projection-matrices
    - qmake -spec linux-clang
    - make

build-readmeTeaser:
  stage: build
  script:
    - cd examples/readme-example
    - qmake
    - make
build-readmeTeaser-clang:
  stage: build
  script:
    - cd examples/readme-example
    - qmake -spec linux-clang
    - make

build-setupVisualizer:
  stage: build
  script:
    - cd examples/setupVisualizer
    - qmake
    - make
build-setupVisualizer-clang:
  stage: build
  script:
    - cd examples/setupVisualizer
    - qmake -spec linux-clang
    - make

build-simTool:
  stage: build
  script:
    - cd examples/simTool
    - qmake
    - make
build-simTool-clang:
  stage: build
  script:
    - cd examples/simTool
    - qmake -spec linux-clang
    - make
build-simTool-Debug:
  stage: build
  script:
    - cd examples/simTool
    - qmake CONFIG+=debug
    - make
build-simTool-Debug-clang:
  stage: build
  script:
    - cd examples/simTool
    - qmake -spec linux-clang CONFIG+=debug
    - make


# unit testing

build-unitTests:
  stage: build
  script:
    - mkdir testing/src/gcc
    - cd testing/src/gcc
    - qmake ..
    - make
  artifacts:
    paths:
      - testing/src/gcc/bin/
build-unitTests-clang:
  stage: build
  script:
    - mkdir testing/src/clang
    - cd testing/src/clang
    - qmake -spec linux-clang ..
    - make
  artifacts:
    paths:
      - testing/src/clang/bin/

run-unitTests:
  stage: test
  script:
    - cd testing/src/gcc/bin
    - ./unitTesting
run-unitTests-clang:
  stage: test
  script:
    - cd testing/src/clang/bin
    - ./unitTesting


# trigger building of documentation

run-doxygen:
  stage: build
  script:
    - wget -q -O start-doxy $INITIATE_DOXY_SCRIPT
    - lynx -cmd_script=start-doxy $DOXY_LOGIN_PAGE > /dev/null
    

# update codes of line analysis
  stage: build
  script:
    - git clone https://gitlab.com/robertFrysch/cntln.git
    - cd cntln && qmake && make && cd ..
    - cntln/cntln    modules testing examples > index.md
    - cntln/cntln -e modules testing examples > empty.md
    - UD=$NC_UPLOAD_DIR
    - curl -T index.md -u $UD -H 'X-Requested-With: XMLHttpRequest' -H 'X-Method-Override: PUT' https://rf.p7.de/public.php/webdav/index.md
    - curl -T empty.md -u $UD -H 'X-Requested-With: XMLHttpRequest' -H 'X-Method-Override: PUT' https://rf.p7.de/public.php/webdav/empty.md

    